version: '3'


tasks:
  default:
    cmds:
      - echo "Building the project"
    deps:
      [ clean, restore, build, publish ]

  clean:
    cmds:
      - rm -rf ./publish
      - dotnet clean
  restore:
    cmds:
      - dotnet restore
  build:
    cmds:
      - dotnet build
  publish:
    cmds:
      - dotnet publish src/EterniaEmu.Server/EterniaEmu.Server.csproj p:PublishSingleFile=true --self-contained true  -c Release -o ./publish
  docker-build:
    cmds:
      - docker buildx build -t eterniaemu .
